### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/crm-addons#11]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] crm_case_category
- [ ] crm_claim_channel
- [ ] crm_claim_close
- [ ] crm_claim_code_by_category
- [ ] crm_claim_company
- [ ] crm_claim_deadline
- [ ] crm_claim_deadline_visible
- [ ] crm_claim_filter
- [ ] crm_claim_phonecall
- [ ] crm_claim_related
- [ ] crm_claim_report
- [ ] crm_claim_security
- [ ] crm_claim_team
- [ ] crm_claim_timesheet
- [ ] crm_lead_customer_payment
- [ ] crm_lead_partner_contact
- [x] crm_lead_show_action (#13)
- [ ] crm_phonecall_reference
- [ ] crm_project
- [ ] website_crm_customer_payment
