### ISSUE TITLE
Migration to version 14.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/crm-addons#53]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

# Modules to migrate

- [ ] crm_claim_analytic
- [ ] crm_claim_kanban_view
- [ ] crm_claim_school
- [ ] crm_extended_address
- [ ] crm_school
- [ ] crm_school_firstname
- [ ] crm_school_permission
- [ ] crm_survey
- [ ] website_crm_extended_address

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
